### ISSUE TITLE
working exemple for rstudio shiny.rmd)

### ISSUE THREAD

**Issue by brunelserge** [htmlwidgets/morris#1]
the main page exemple isn't working in Rstudio when you click  run document
this one is working

---

title: "Untitled"
author: "serge"
date: "Monday, August 04, 2014"
output: html_document
## runtime: shiny

``` r, echo=FALSE

library(shiny)
library(htmlwidgets)
library(morris)

dat = data.frame(
  year = as.character(2008:2012),
  value = c(20, 10, 5, 5, 20)
)

inputPanel(
   selectInput('type', 'Choose Type', c('Line', 'Bar')),
   textInput('units', 'Choose', 'Km'),
   morrisOutput('myplot', 600, 400)

)

output$myplot <-renderWidget({
    morris(value ~ year, data = dat, type = input$type, labels = list("Value"),
      yLabelFormat = sprintf("function(y){return y.toString() + ' %s'}", 
        input$units)       
    )
})
```

**Comment by ramnathv** [comment]
Thanks for the Rmd example. The example in the README is for running a Shiny app from an R script, not for inside an Rmd document. So if you run it in your R console, it should work.
